---
title: "Ihaka Lecuture Series 2017"
author: "Lars Schoebitz"
date: "10 March 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Expressing yourself with R

https://www.youtube.com/watch?v=1POb5fx_m3I&feature=youtu.be

> What's the difference between an introverted and an extroverted statistician? The extroverted looks at somebody else's shoes. - Peter Donley

The hitchehikers guide to the hadleyverse.

## Intro

- how can you most easily express yourself in R
- rich underlying theory
- try something and it just works
- solving complex problems in simple pieces
- fail R as quickly as possible
- check your work after each step

## R code example slide

- what's wrong with this code? where are the mistakes
- intend of the code: negative values are 99
- wrong: copy/pasting errors.
- unit of problem solving in R is a function
- purrr::modify_if

## simple pieces

- what makes a function simple
- two key ideas behind simple functions
    - one thing well
    - minimal context
    
- mutate() is called primarily because it returns a value.
- 